"""empty message

Revision ID: 5b9c3478c1ff
Revises: cfb0c549a9c6
Create Date: 2023-04-04 21:19:28.832955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b9c3478c1ff'
down_revision = 'cfb0c549a9c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_hash', sa.String(length=128), nullable=True))
        batch_op.drop_column('senha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', mysql.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('senha_hash')

    # ### end Alembic commands ###
