"""empty message

Revision ID: ee468df1ebd5
Revises: 
Create Date: 2023-03-16 21:26:53.596738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee468df1ebd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motorista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=32), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('carro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fabricante', sa.String(length=32), nullable=False),
    sa.Column('modelo', sa.String(length=16), nullable=False),
    sa.Column('placa', sa.String(length=8), nullable=False),
    sa.Column('dono_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dono_id'], ['motorista.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carro')
    op.drop_table('motorista')
    # ### end Alembic commands ###
