"""empty message

Revision ID: 1253c476e4eb
Revises: ee468df1ebd5
Create Date: 2023-03-16 21:43:50.865309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1253c476e4eb'
down_revision = 'ee468df1ebd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('motivo', sa.String(length=32), nullable=True),
    sa.Column('pontos', sa.Integer(), nullable=True),
    sa.Column('gravidade', sa.Integer(), nullable=True),
    sa.Column('motorista_id', sa.Integer(), nullable=True),
    sa.Column('carro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carro_id'], ['carro.id'], ),
    sa.ForeignKeyConstraint(['motorista_id'], ['motorista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multa')
    # ### end Alembic commands ###
