"""empty message

Revision ID: b188f38c1a98
Revises: 100e29c72d9d
Create Date: 2023-04-13 20:42:31.740852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b188f38c1a98'
down_revision = '100e29c72d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=16), nullable=False),
    sa.Column('perm', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('papel_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'papel', ['papel_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('papel_id')

    op.drop_table('papel')
    # ### end Alembic commands ###
